### ISSUE TITLE
just empty line in callback argument of add.torrent({callback: function(ReadToUseTorrent){}} instead of torrent model

### ISSUE THREAD

**Issue by arestov** [bittorrenttorque/btapp#6]
``` javascript
add.torrent({
    url: test_link,
    callback: function(trt){
        trt === '' //:(((
    }
})
```

expect torrent model in "trt".

How I can get  exactly torrent I've added?

**Comment by pwmckenna** [comment]
ah yes...i need to improve that field. the most basic thing that I'll try to do asap is make it return an object {hash:XXXXXXX....} so that the hash can be used to lookup the model on the javascript side. 

down the line it would be nice if the underlying client returned information indicating to btapp.js that it should fill in that value with an existing backbone model. that would be really nice for add/create calls.

i'll treat the empty return value as a bug, and try to make sure at least there is useful information in the return value.
